(function(){
  "use strict";
  var ADMIN_EMAIL="ansarmedia@ansarschool.in",config=window.ANSAR_FIREBASE_CONFIG||{};
  var loginView=document.getElementById("login-view"),adminView=document.getElementById("admin-view"),loginMessage=document.getElementById("login-message"),formMessage=document.getElementById("form-message");
  function message(el,text,error){el.textContent=text||"";el.classList.toggle("error",!!error)}
  if(!config.apiKey||config.apiKey==="REPLACE_ME"){message(loginMessage,"Firebase must be configured before the admin portal can be used. See README.md.",true);document.getElementById("login-button").disabled=true;return}
  firebase.initializeApp(config);var auth=firebase.auth(),db=firebase.firestore(),provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({prompt:"select_account",hd:"ansarschool.in",login_hint:ADMIN_EMAIL});
  document.getElementById("login-button").onclick=function(){message(loginMessage,"Opening secure sign-in…");auth.signInWithPopup(provider).catch(function(e){message(loginMessage,friendly(e),true)})};
  document.getElementById("logout-button").onclick=function(){auth.signOut()};
  function friendly(e){if(e&&e.code==="auth/popup-blocked")return "The sign-in popup was blocked. Allow popups and try again.";if(e&&e.code==="auth/popup-closed-by-user")return "Login was cancelled before an account was selected.";if(e&&e.code==="auth/operation-not-allowed")return "Google login must be enabled in Firebase Authentication.";if(e&&e.code==="auth/unauthorized-domain")return "Login is not authorised for this website yet. Add d3ztudio-cpu.github.io to Firebase Authentication → Settings → Authorized domains.";return (e&&e.message)||"Something went wrong. Please try again."}
  auth.onAuthStateChanged(async function(user){
    if(!user){loginView.hidden=false;adminView.hidden=true;return}
    var loginEmail=(user.email||"").trim().toLowerCase();
    if(loginEmail!==ADMIN_EMAIL||user.emailVerified!==true){await auth.signOut();message(loginMessage,"Access denied. Please select "+ADMIN_EMAIL+". Other accounts cannot open the venue editor.",true);return}
    loginView.hidden=true;adminView.hidden=false;document.getElementById("signed-in-email").textContent=user.email;startEditor();
  });
  var started=false,map,markers=L.layerGroup(),draftMarker,venues=[];
  var fields={id:document.getElementById("venue-id"),name:document.getElementById("venue-name"),description:document.getElementById("venue-description"),category:document.getElementById("venue-category"),floor:document.getElementById("venue-floor"),lat:document.getElementById("venue-lat"),lng:document.getElementById("venue-lng"),active:document.getElementById("venue-active")};
  function startEditor(){if(started){setTimeout(function(){map.invalidateSize()},0);return}started=true;map=L.map("admin-map",{maxBounds:L.latLngBounds([10.6983,76.0869],[10.7015,76.0919]),maxBoundsViscosity:.8}).setView([10.69947,76.08935],19);var normal=L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{minZoom:17,maxZoom:21,attribution:'&copy; OpenStreetMap'}).addTo(map);var satellite=L.tileLayer("https://{s}.google.com/vt?lyrs=s&x={x}&y={y}&z={z}",{minZoom:17,maxZoom:21,subdomains:["mt0","mt1","mt2","mt3"]});L.control.layers({Map:normal,Satellite:satellite}).addTo(map);markers.addTo(map);map.on("click",function(e){clearForm();setCoordinates(e.latlng);fields.name.focus()});setTimeout(function(){map.invalidateSize()},0);db.collection("venues").onSnapshot(async function(s){venues=[];s.forEach(function(d){venues.push(Object.assign({id:d.id},d.data()))});if(s.empty){await importInitialVenues();return}render()},function(e){message(formMessage,friendly(e),true)})}
  async function importInitialVenues(){try{var data=await fetch("data/venues.json").then(function(r){return r.json()}),batch=db.batch();data.forEach(function(v){var copy=Object.assign({},v);delete copy.id;copy.updatedAt=firebase.firestore.FieldValue.serverTimestamp();batch.set(db.collection("venues").doc(v.id),copy)});await batch.commit();message(formMessage,"Initial venues imported. You can now edit them.")}catch(e){message(formMessage,"Could not import initial venues: "+friendly(e),true)}}
  function icon(category,inactive){return L.divIcon({className:"venue-marker "+(category||"other"),html:'<span style="opacity:'+(inactive?".35":"1")+'"></span>',iconSize:[30,30],iconAnchor:[15,15]})}
  function render(){markers.clearLayers();venues.sort(function(a,b){return a.name.localeCompare(b.name)}).forEach(function(v){var marker=L.marker([v.lat,v.lng],{icon:icon(v.category,v.active===false),draggable:true}).addTo(markers);marker.bindTooltip(v.name);marker.on("click",function(){select(v)});marker.on("dragend",function(){select(v);setCoordinates(marker.getLatLng());message(formMessage,"Position changed. Click Save venue to publish it.")})});var list=document.getElementById("venue-list");list.textContent="";venues.forEach(function(v){var button=document.createElement("button"),text=document.createElement("span"),title=document.createElement("strong"),small=document.createElement("small");button.type="button";title.textContent=v.name;small.textContent=[v.category,v.floor].filter(Boolean).join(" · ");text.append(title,small);button.appendChild(text);if(v.active===false){var badge=document.createElement("span");badge.className="inactive-badge";badge.textContent="Hidden";button.appendChild(badge)}button.onclick=function(){select(v);map.setView([v.lat,v.lng],20)};list.appendChild(button)});document.getElementById("venue-count").textContent=venues.length}
  function setCoordinates(ll){fields.lat.value=Number(ll.lat).toFixed(7);fields.lng.value=Number(ll.lng).toFixed(7);if(draftMarker)map.removeLayer(draftMarker);draftMarker=L.marker(ll,{icon:icon(fields.category.value,false)}).addTo(map)}
  function select(v){fields.id.value=v.id;fields.name.value=v.name||"";fields.description.value=v.description||"";fields.category.value=v.category||"other";fields.floor.value=v.floor||"";fields.active.checked=v.active!==false;fields.lat.value=v.lat;fields.lng.value=v.lng;document.getElementById("delete-button").hidden=false;if(draftMarker){map.removeLayer(draftMarker);draftMarker=null}message(formMessage,"")}
  function clearForm(){document.getElementById("venue-form").reset();fields.id.value="";fields.active.checked=true;document.getElementById("delete-button").hidden=true;message(formMessage,"Click Save venue after entering the details.")}
  document.getElementById("new-button").onclick=function(){clearForm();if(draftMarker){map.removeLayer(draftMarker);draftMarker=null}};
  document.getElementById("venue-form").onsubmit=async function(e){e.preventDefault();var lat=Number(fields.lat.value),lng=Number(fields.lng.value);if(!Number.isFinite(lat)||!Number.isFinite(lng)){message(formMessage,"Choose a valid position on the map.",true);return}var data={name:fields.name.value.trim(),description:fields.description.value.trim(),category:fields.category.value,floor:fields.floor.value.trim(),lat:lat,lng:lng,active:fields.active.checked,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};try{message(formMessage,"Saving…");var ref=fields.id.value?db.collection("venues").doc(fields.id.value):db.collection("venues").doc();await ref.set(data,{merge:true});fields.id.value=ref.id;document.getElementById("delete-button").hidden=false;if(draftMarker){map.removeLayer(draftMarker);draftMarker=null}message(formMessage,"Venue saved and published.")}catch(err){message(formMessage,friendly(err),true)}};
  document.getElementById("delete-button").onclick=async function(){var id=fields.id.value,name=fields.name.value;if(!id||!confirm('Delete "'+name+'" from the map?'))return;try{await db.collection("venues").doc(id).delete();clearForm();message(formMessage,"Venue deleted.")}catch(e){message(formMessage,friendly(e),true)}};
})();
